// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ScrollTo(id string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ScrollTo_ef2e`,
		Function: `function __templ_ScrollTo_ef2e(id){const targetRect = me(id).getBoundingClientRect();
    const bodyRect = document.body.getBoundingClientRect();
    const headerRect = me("#header").getBoundingClientRect();

    if (window.innerHeight < targetRect.height) {
        const top = targetRect.top + headerRect.height - bodyRect.top;
        window.scrollTo({ top: top - window.innerHeight/2, behavior: "smooth" });
    } else {
        const top = targetRect.top + targetRect.height/2 - bodyRect.top;
        window.scrollTo({ top: top - window.innerHeight/2, behavior: "smooth" });
    }
}`,
		Call:       templ.SafeScript(`__templ_ScrollTo_ef2e`, id),
		CallInline: templ.SafeScriptInline(`__templ_ScrollTo_ef2e`, id),
	}
}

var _ = templruntime.GeneratedTemplate
